### ISSUE TITLE
[👨🏻‍💻Task] 레시피 작성 - 재료 담기 슬라이드

### ISSUE THREAD

**Issue by Sanso22** [codestates/Bobpago#11]
### ISSUE
- Group:  client
- Type: feature
- Detail: 레시피 작성 - 재료 담기 슬라이드

### TODO
1. [x] Autocomplete 검색창 구현
2. [x] 검색창 css 효과 구현
3. [x] 태그 형식의 담긴 재료 목록 구현
4. [x] 재료 목록 css 효과 구현
