### ISSUE TITLE
[👨🏻‍💻Task] 도메인 구입 및 https 설정

### ISSUE THREAD

**Issue by pinion7** [codestates/Bobpago#16]
### ISSUE
- Group:  server
- Type: feature
- Detail: 도메인 구입 및 https 설정

### TODO
1. [ ] AWS Route 53 도메인 구입 및 등록
2. [ ] https 세팅을 위한 AWS CM인증서 발급
3. [ ] AWS Cloud Front, Load Balancer 세팅
4. [ ] 1~3 세팅을 기반으로 Route 53 호스팅 영역 세팅 및 EC2 포트 개방 인바운드 규칙 설정 ->  https 연결 완료

### Estimated time
Pick one
### Labels
- Estimated time: E: 2h
- Group : server
- Sprint: Sprint1
- Urgency: Middle
