### ISSUE TITLE
[👨🏻‍💻Task] 랜딩 소개 페이지 구현

### ISSUE THREAD

**Issue by VVSOGI** [codestates/Bobpago#17]
### ISSUE
- Group:  client
- Type: feature
- Detail: 랜딩 페이지에서 프론트 엔드에 대한 평가가 1초안에 갈린다는 피드백을 들었다. 프로젝트의 첫 단추같은 부분이기 때문에,
스크롤에 의한, 다양한 애니메이션이 구성될 것이다. 통일된 느낌으로 임팩트 있게 보여주게끔 노력한다.
getBoundingClientRect().top을 이용해보자.

### TODO
1. [x] 보이지 않던 아이템이 transition을 이용해서 서서히 들어나게끔 하기.
2. [x] 작은 이미지들을 배경 효과로 이용하기.
3. [x] onScroll 이벤트 최적화를 적용하기.

### Estimated time
Pick one
### Labels
- Estimated time: E: 3h
- Group : client
- Sprint: Sprint3
- Urgency: High
