### ISSUE TITLE
[👨🏻‍💻Task] 레시피 작성 - 레시피 작성 슬라이드 css

### ISSUE THREAD

**Issue by Sanso22** [codestates/Bobpago#19]
### ISSUE
- Group:  client
- Type: feature
- Detail: 레시피 작성 - 레시피 작성 슬라이드

### TODO
1. [x] 이미지 올리기 (기능 + css)
2. [x] 레시피 순서대로 작성 (css)
3. [x] 추가 작성 버튼
