### ISSUE TITLE
[👨🏻‍💻Task] 레시피 매인 페이지 구현

### ISSUE THREAD

**Issue by VVSOGI** [codestates/Bobpago#20]
### ISSUE
- Group:  client
- Type: feature
- Detail: 레시피 메인 페이지는 설문조사를 마친 유저가 이동하는 페이지이다. 설계를 어떻게 하느냐에 따라서 설문조사 페이지와 메인 페이지를
하나로 묶어서 페이지 트랜지션 효과를 줄 수도 있을 것 같지만, 일단은 use-history로 페이지를 아예 이동하는 느낌을 주는걸로 베어 미니멈을
구성한다. 요리 경험이 없는 유저 페이지와 경험이 있는 유저 페이지를 나눠야 한다. 경험이 없는 유저는 선택할 수 있는 재료가 적은 숫자로
재료 사진과 큰 버튼으로 만든다. 경험이 있는 유저는 작은 버튼에 우선 사진 없이 그리고 재료들을 서버에서 받은 후에 카테고리 별로 재료를
나눠서 볼 수 있게끔 구성한다. 또한, 경험이 있는 유저는 재료를 검색해서 찾을 수 있게끔 한다.

### TODO
1. [x] 요리 경험이 없는 유저의 메인 페이지 구현.
2. [x] 요리 경험이 있는 유저의 메인 페이지 구현.
3. [x] 요리 경험이 있는 유저의 카테고리 필터 기능 구현.
4. [x] 요리 경험이 있는 유저의 재료 검색 자동 완성 기능 구현.
