### ISSUE TITLE
[👨🏻‍💻Task] 레시피 매칭 페이지 구현

### ISSUE THREAD

**Issue by VVSOGI** [codestates/Bobpago#21]
### ISSUE
- Group:  client
- Type: feature
- Detail: 레시피 매칭 페이지는 앞서 사용자들이 선택했던 재료들을 토대로 가장 알맞은 레시피들을 알려주는 페이지이다.
로딩 이후에 매칭 페이지가 나와야하는데, 처음으로 매칭 페이지가 랜딩이 될 때 오른쪽에서 왼쪽으로 빨랫줄에 걸려있듯이 애니메이션 효과를 
준다. settimeout과 styled-components를 이용하면 될 것이다. 그리고 여기는 horizontal scroll effect를 사용해야 한다.
좌우로 움직이는 스크롤을 잘 이용해보자. 

### TODO
1. [x] 좌우로 레시피 매칭  결과를 보여주는 호라이젠탈 스크롤 구현
2. [x] 빨랫줄 뒷 배경 구해오기.
3. [x] 페이지 랜딩할 때, 오른쪽 화면 밖에서 화면 안으로 레시피들이 차례대로 들어오는 효과 구현,
