### ISSUE TITLE
[👨🏻‍💻Task] 레시피 작성 - 반응형 웹

### ISSUE THREAD

**Issue by Sanso22** [codestates/Bobpago#25]
### ISSUE
- Group:  client
- Type: feature
- Detail: 레시피 작성 - 반응형 웹

### TODO
1. [x] 제목, 버튼, 입력  위치 조정
2. [x] 툴팁 위치 조정
3. [x] 글자 크기, 버튼 크기 등 크기 조정
4. [x] 레시피 작성 슬라이드 - 이미지를 위로 글씨작성을 아래로 조정
