### ISSUE TITLE
[👨🏻‍💻Task] typeorm을 이용한 mysql database 연결

### ISSUE THREAD

**Issue by tjdgns5272** [codestates/Bobpago#34]
### ISSUE
- Group:  server, db
- Type: feature
- Detail: typeorm을 이용한 mysql database 연결

### TODO
1. [x] typeorm 설치
2. [x] 자동 동기화 설정
3. [x] 테이블 속성 작성
4. [x] 테이블 관계 설정
