### ISSUE TITLE
[👨🏻‍💻Task] 기술 스택 공부 - Redux

### ISSUE THREAD

**Issue by Sanso22** [codestates/Bobpago#37]
### ISSUE
- Group:  client
- Type: feature
- Detail: Redux 공부

### TODO
1. [x] 이전 sprint보면서 전체적으로 복습
2. [x] redux-logger 공부
3. [x] redux-saga, redux-thunk 공부하면서 어떤 것이 더 나을지 비교, 비동기 처리 공부
4. [x] redux-persist 공부
