### ISSUE TITLE
[👨🏻‍💻Task] 레시피 작성 - 요리 제목 입력 슬라이드

### ISSUE THREAD

**Issue by Sanso22** [codestates/Bobpago#4]
### ISSUE
- Group:  client
- Type: feature
- Detail: 레시피 작성 - 요리 제목 입력 슬라이드, 입력 부분은 돋보기 모양 버튼을 누르면 입력창이 

### TODO
1. [x] 제목에 대한 질문 작성
2. [x] 제목 입력 칸 focus 효과 구현
3. [x] 전체 레시피 작성 페이지에 대한 슬라이드 구현
