### ISSUE TITLE
[👨🏻‍💻Task] 클라이언트 환경 구축 - 라이브러리 설치

### ISSUE THREAD

**Issue by Sanso22** [codestates/Bobpago#46]
### ISSUE
- Group:  client
- Type: feature
- Detail: 클라이언트 환경 구축

### TODO
1. [x] redux 관련 라이브러리 설치(redux, react-redux, redux-persist, redux-logger, redux-thunk, redux-devtools-extension)
2. [x] typescript 관련 라이브러리 설치(@types/react, @types/react-dom, typescript, @types/react-redux @types/redux-actions, redux-actions)
3. [x] postcss 관련 라이브러리 설치(@craco/craco)
4. [x] styled-component 라이브러리 설치
