### ISSUE TITLE
[👨🏻‍💻Task] 회원가입 모달 

### ISSUE THREAD

**Issue by Sanso22** [codestates/Bobpago#56]
### ISSUE
- Group:  client,
- Type: feature
- Detail: 회원가입 모달 

### TODO
1. [ ] 이메일, 닉네임, 패스워드, 패스워드 확인 입력 - css 구현
2. [ ] 회원가입 버튼 이펙트
2. [ ] 유효성 검사
3. [ ] 유효성 검사로 인한 오류 메세지 구현
