### ISSUE TITLE
[👨🏻‍💻Task] 상세 페이지 구현

### ISSUE THREAD

**Issue by VVSOGI** [codestates/Bobpago#62]
### ISSUE
- Group:  client
- Type: feature
- Detail: 상세 페이지를 구현할 때, 100vh단위의 여러개의 section들이 위아래로 붙어있는 형식을 만들어야한다.
또한 페이지당 가지고있는 작은 컴포넌트들도 section의 갯수만큼 위아래로 붙여주고 overflow는 hidden으로 한다.
gsap을 이용해서 full page 이동할 때, 안 쪽의 작은 컴포넌트들도 같이 위아래로 이동하는 형식을 구현한다.

### TODO
1. [ ] 데이터 호출 시에 여러개의 section을 map으로 구현하기.
2. [ ] gsap을 이용한 full page 움직임 구현.
3. [ ] full page 이동시에 작은 컴포넌트들도 같이 움직임.
