### ISSUE TITLE
[👨🏻‍💻Task] API 문서 작성

### ISSUE THREAD

**Issue by pinion7** [codestates/Bobpago#8]
### ISSUE
- Group: client, server
- Type: feature
- Detail: 프론트, 백이 협력하여 API 문서 작성

### TODO
1. [x] API flow charts에 따른 문서 종류 구분 및 기본 세팅
2. [x] API 요청시 전달해줘야할 헤더, 바디, 파라미터 등 세팅
3. [x] API 응답시 전달해줘야할 데이터, 메시지 등 세팅

### Estimated time
Pick one
### Labels
- Estimated time: E: 3h
- Group : client, server
- Sprint: Sprint1
- Urgency: Middle
