### ISSUE TITLE
[👨🏻‍💻Task] 레시피 작성 - 예상 조리시간 슬라이드 구현

### ISSUE THREAD

**Issue by Sanso22** [codestates/Bobpago#9]
### ISSUE
- Group:  client
- Type: feature
- Detail: 레시피 작성 - 예상 조리시간 슬라이드 구현

### TODO
1. [x] 시간버튼(input:radio) 마다 focus 구현
2. [x] 기타입력, 난이도 자동설정에 대한 경고 툴팁 구현
3. [x] 기타입력칸 focus 효과 구현
